pipeline:
  build:
    image: python:3.7
    commands:
      - python -m pip install -r requirements.txt
      - python -m pip install codecov
      - python -m pip install -e .
      - bash run-tests.sh
      - codecov -t $CODECOV_TOKEN
    secrets: [ codecov_token ]